-- StreamKernel Snowpipe Streaming smoke queries

SELECT
    PIPELINE_ID,
    COUNT(*) AS ROW_COUNT,
    MIN(EVENT_TS) AS FIRST_EVENT_TS,
    MAX(EVENT_TS) AS LAST_EVENT_TS
FROM STREAMKERNEL.PUBLIC.ENRICHED_EVENTS
GROUP BY PIPELINE_ID
ORDER BY LAST_EVENT_TS DESC;

SELECT
    EVENT_ID,
    EVENT_KEY,
    EVENT_TS,
    PAYLOAD_TYPE,
    SOURCE_TEXT,
    ARRAY_SIZE(EMBEDDING) AS EMBEDDING_DIM,
    PIPELINE_ID,
    RUN_ID,
    SOURCE_AUTH,
    SINK_AUTH,
    CONFIG_SHA256
FROM STREAMKERNEL.PUBLIC.ENRICHED_EVENTS
ORDER BY EVENT_TS DESC
LIMIT 20;
